hypertrace/hypertrace-core-graphql

hypertrace-core-graphql-service/src/main/java/org/hypertrace/core/graphql/service/GraphQlService.java

First observed after updating platform service framework dependency

fix: NPE due to service name getter override

---

hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/schema/CommonSchemaFragment.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/schema/typefunctions/TimeScalar.java
hypertrace-core-graphql-common-schema/src/test/java/org/hypertrace/core/graphql/common/schema/scalars/TimeScalarTest.java

Supports Time Scalar without Date such as 08:00.
This is useful to specify schedule rather than a temporal date time.

Adds Time Scalar

---

hypertrace-core-graphql-attribute-store/build.gradle.kts
hypertrace-core-graphql-attribute-store/src/main/java/org/hypertrace/core/graphql/attributes/AttributeStoreModule.java
hypertrace-core-graphql-attribute-store/src/main/java/org/hypertrace/core/graphql/attributes/CachingAttributeStore.java
hypertrace-core-graphql-attribute-store/src/main/java/org/hypertrace/core/graphql/attributes/IdLookup.java
hypertrace-core-graphql-attribute-store/src/main/java/org/hypertrace/core/graphql/attributes/IdMappingLoader.java
hypertrace-core-graphql-attribute-store/src/test/java/org/hypertrace/core/graphql/attributes/CachingAttributeStoreTest.java
hypertrace-core-graphql-attribute-store/src/test/java/org/hypertrace/core/graphql/attributes/IdLookupTest.java

this change allows id mappings to be added dynamically without
explicitly listing them out in the guice module config. This is meant to
unlock support for features like tenant-scoped entities and dynamically
created entity types.

feat: support dynamic id mappings

---

hypertrace-core-graphql-attribute-store/src/main/java/org/hypertrace/core/graphql/attributes/AttributeModel.java
hypertrace-core-graphql-attribute-store/src/main/java/org/hypertrace/core/graphql/attributes/AttributeModelTranslator.java
hypertrace-core-graphql-attribute-store/src/main/java/org/hypertrace/core/graphql/attributes/DefaultAttributeModel.java
hypertrace-core-graphql-attribute-store/src/test/java/org/hypertrace/core/graphql/attributes/AttributeModelTranslatorTest.java
hypertrace-core-graphql-metadata-schema/src/main/java/org/hypertrace/core/graphql/metadata/response/DefaultAttributeMetadata.java
hypertrace-core-graphql-metadata-schema/src/main/java/org/hypertrace/core/graphql/metadata/response/MetadataResponseBuilder.java
hypertrace-core-graphql-metadata-schema/src/main/java/org/hypertrace/core/graphql/metadata/schema/AttributeMetadata.java
hypertrace-core-graphql-metadata-schema/src/test/java/org/hypertrace/core/graphql/metadata/response/MetadataResponseBuilderTest.java

This change exposes a new piece of metadata `onlySupportsAggregation`) whether an attribute must be aggregated in its metadata. There was an existing attribute with an extremely confusing name and different meaning, `onlyAggregationsAllowed` that was deprecated and instead renamed to a more accurate name, `onlySupportsGrouping`. 
The prior attribute (now known as `onlySupportsGrouping`) indicates an attribute is only available in a grouped query (which also implicitly means an aggregation). The new attribute (`onlySupportsAggregation`) indicates an attribute requires an aggregation in any query, whether grouped or row level. Descriptions have been added to reflect this.
This will be used in the UI to programmatically build table columns based on available attribute metadata.
Unit tests …

feat: expose if an attribute can be aggregated in metadata

---

hypertrace-core-graphql-deserialization/src/main/java/org/hypertrace/core/graphql/deserialization/ArgumentDeserializationConfig.java
hypertrace-core-graphql-deserialization/src/main/java/org/hypertrace/core/graphql/deserialization/DefaultArgumentDeserializer.java
hypertrace-core-graphql-deserialization/src/main/java/org/hypertrace/core/graphql/deserialization/SimpleArgumentDeserializationConfig.java
hypertrace-core-graphql-deserialization/src/test/java/org/hypertrace/core/graphql/deserialization/DefaultArgumentDeserializerTest.java

Support using a different argument name when deserializing a list of arguments vs a single arg
Updated unit tests

fix: support a different arg name for plural args

---

.github/workflows/pr-build.yml

Remove config filter for graphql - not needed here. It was an optimization (and avoided enforcing extra strict checks on test deps), but looks like snyk requires it match every project. Because graphql uses a platform project (which apparently snyk doesn't have built in support for) it has a project that does not have its own runtimeClasspath. 
I also tried changing the regex to make it less strict, but even something like `runtime` or `.*runtime.*` is not matching:
```
> Matching configurations not found: runtime, available configurations for project project ':hypertrace-core-graphql-platform': [api, apiElements, archives, classpath, default, enforcedApiElements, enforcedRu
ntimeElements, runtime, runtimeElements]
```
Ran snyk locally successfully

ci: fix snyk args to match all configs

---

.github/workflows/publish.yml

removes publish from gradle publish as this repo doesn't have publish.

fix: publish for docker images

---

hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/schema/CommonSchemaFragment.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/schema/typefunctions/DurationScalar.java
hypertrace-core-graphql-common-schema/src/test/java/org/hypertrace/core/graphql/common/schema/scalars/DurationScalarTest.java

Adds support for a duration scalar using the ISO-8601 format for transport (matching what we already due for instant)
Added unit tests, also added to a schema and spun up to verify the integration.

feat: add duration scalar support

---

hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/dao/SpanLogEventDao.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/dao/SpanLogEventRequestBuilder.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/dao/SpanLogEventResponseConverter.java
hypertrace-core-graphql-span-schema/src/test/java/org/hypertrace/core/graphql/span/dao/SpanLogEventRequestBuilderTest.java
hypertrace-core-graphql-span-schema/src/test/java/org/hypertrace/core/graphql/span/dao/SpanLogEventResponseConverterTest.java

feat: Add spanId attribute for span-log join query

---

hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/request/CommonRequestModule.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/request/ContextualRequest.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/request/ContextualRequestBuilder.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/request/ResultSetRequest.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/request/SimpleContextualRequestBuilder.java
hypertrace-core-graphql-log-event-schema/src/main/java/org/hypertrace/core/graphql/log/event/request/LogEventRequest.java
hypertrace-core-graphql-trace-schema/src/main/java/org/hypertrace/core/graphql/trace/request/TraceRequest.java

We often duplicate request objects per api on get requests without params - this common builder allows using a pre-existing request in those cases.

refactor: add a simple context request to simplify queries

---

hypertrace-core-graphql-deserialization/build.gradle.kts
hypertrace-core-graphql-deserialization/src/main/java/org/hypertrace/core/graphql/deserialization/DefaultArgumentDeserializer.java
hypertrace-core-graphql-platform/build.gradle.kts

Throughout the gql modules we avoid using null and instead use safer constructs like Optional and Maybe to handle presence. In the schema, nullability is handled through annotations, but within the code we would like to keep the objects consistent with the rest of the code. graphql-java-annotations already supports this, so here we bring our deserializer in line.
Manually verified with an optional type

feat: add support for optional tyoe usage in schema

---

hypertrace-core-graphql-gateway-service-utils/src/main/java/org/hypertrace/core/graphql/utils/gateway/SelectionExpressionSetConverter.java
hypertrace-core-graphql-service/build.gradle.kts
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/dao/SpanLogEventRequestBuilder.java
hypertrace-core-graphql-span-schema/src/test/java/org/hypertrace/core/graphql/span/dao/DaoTestUtil.java
hypertrace-core-graphql-span-schema/src/test/java/org/hypertrace/core/graphql/span/dao/SpanLogEventRequestBuilderTest.java

Fetching the logs to join into a span request previously did not provide a limit, meaning it limited to 10 logs total across all spans in the request. Instead, requesting up to 1000 now. Changed the tests to match objects rather than fields, which is more robust as it catches unintended fields too (adding a new field like limit should have failed the test, and didn't before this change). Also tweaked a few things in other places to support predictable iteration order.
UTs

fix: apply limit on span log fetch

---

hypertrace-core-graphql-log-event-schema/src/main/java/org/hypertrace/core/graphql/log/event/dao/GatewayServiceLogEventDao.java
hypertrace-core-graphql-service/src/main/java/org/hypertrace/core/graphql/service/DefaultGraphQlServiceConfig.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/dao/GatewayServiceSpanDao.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/dao/SpanDaoModule.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/dao/SpanLogEventDao.java
hypertrace-core-graphql-spi/src/main/java/org/hypertrace/core/graphql/spi/config/GraphQlServiceConfig.java
hypertrace-core-graphql-trace-schema/src/main/java/org/hypertrace/core/graphql/trace/dao/GatewayServiceTraceDao.java

These changes are in context of: hypertrace/hypertrace-core-graphql#69. Currently, we hardcode the deadline as 10s. Now, GATEWAY_SERVICE_DEADLINE is read from application.conf
Deployed and tested the application manually. I am still seeing if I can write a UT for check if config value is being loaded properly.
These changes are dependent on: https://github.com/hypertrace/hypertrace-service/pull/99

Gateway-Service Client Timeout Config

---

.snyk
hypertrace-core-graphql-attribute-store/src/main/java/org/hypertrace/core/graphql/attributes/AttributeClient.java
hypertrace-core-graphql-service/src/main/java/org/hypertrace/core/graphql/service/DefaultGraphQlServiceConfig.java
hypertrace-core-graphql-spi/src/main/java/org/hypertrace/core/graphql/spi/config/GraphQlServiceConfig.java

Like the PR [here](https://github.com/hypertrace/hypertrace-graphql/pull/91/files), this change is to make client timeout for the Attribute Service configurable.
Deployed and tested the application locally. Scenarios:
1. Missing config: Default timeout is used.
2. Timeout configured: Configured value is used.

Attribute Service Client Configurable Timeout

---

hypertrace-core-graphql-grpc-utils/src/main/java/org/hypertrace/core/graphql/utils/grpc/DefaultGrpcChannelRegistry.java

The grpc channel registry was lifted from graphql and made common, and has since been improved to properly wait for shutdown to complete, which is a change we want to propagate back. Using a delegate model to leave the existing shutdown integration and save from changing all consumers.
Left existing UTs in place

refactor: use common channel registry

---

hypertrace-core-graphql-attribute-store/src/main/java/org/hypertrace/core/graphql/attributes/CachingAttributeStore.java
hypertrace-core-graphql-attribute-store/src/test/java/org/hypertrace/core/graphql/attributes/CachingAttributeStoreTest.java
hypertrace-core-graphql-platform/build.gradle.kts

Reverts hypertrace/hypertrace-core-graphql#78
Attribute Service metadata filter https://github.com/hypertrace/attribute-service/pull/106 does not take care of the backward compatibility for attributes not having `internal` flag, leading to missing attributes while applying the `internal: false` filter in GraphQl

Revert "Filter out internal attributes using the internal flag"

---

hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/schema/CommonSchemaFragment.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/schema/typefunctions/OffsetTimeScalar.java
hypertrace-core-graphql-common-schema/src/test/java/org/hypertrace/core/graphql/common/schema/scalars/DateTimeScalarTest.java
hypertrace-core-graphql-common-schema/src/test/java/org/hypertrace/core/graphql/common/schema/scalars/OffsetTimeScalarTest.java

Add OffsetTime as Typefunction like DateTimeScalar

Add offsetTime Scalar to Typefunction

---

hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/request/AttributeRequest.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/request/DefaultAttributeRequestBuilder.java
hypertrace-core-graphql-common-schema/src/test/java/org/hypertrace/core/graphql/common/request/DefaultAttributeRequestBuilderTest.java
hypertrace-core-graphql-gateway-service-utils/src/main/java/org/hypertrace/core/graphql/utils/gateway/AttributeExpressionConverter.java
hypertrace-core-graphql-gateway-service-utils/src/main/java/org/hypertrace/core/graphql/utils/gateway/AttributeMapConverter.java
hypertrace-core-graphql-gateway-service-utils/src/main/java/org/hypertrace/core/graphql/utils/gateway/SelectionExpressionSetConverter.java
hypertrace-core-graphql-log-event-schema/src/test/java/org/hypertrace/core/graphql/log/event/dao/BaseDaoTest.java
hypertrace-core-graphql-platform/build.gradle.kts
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/dao/GatewayServiceSpanConverter.java
hypertrace-core-graphql-span-schema/src/test/java/org/hypertrace/core/graphql/span/dao/DaoTestUtil.java
hypertrace-core-graphql-span-schema/src/test/java/org/hypertrace/core/graphql/span/dao/SpanLogEventRequestBuilderTest.java
hypertrace-core-graphql-span-schema/src/test/java/org/hypertrace/core/graphql/span/dao/SpanLogEventResponseConverterTest.java
hypertrace-core-graphql-trace-schema/src/main/java/org/hypertrace/core/graphql/trace/dao/GatewayServiceTraceConverter.java

Simple rename requested in  https://github.com/hypertrace/hypertrace-graphql/pull/128

refactor: attribute association expression rename

---

hypertrace-core-graphql-gateway-service-utils/src/main/java/org/hypertrace/core/graphql/utils/gateway/GatewayUtilsModule.java
hypertrace-core-graphql-gateway-service-utils/src/main/java/org/hypertrace/core/graphql/utils/gateway/OperatorConverter.java

Filter Operator Type Converter is required in many places and currently its code is being duplicated.
Added a guice binding so that it can be re-used by the consumers of gateway-service-utils.

Made OperatorConverter public and added a binding for the same.

---

hypertrace-core-graphql-gateway-service-utils/src/main/java/org/hypertrace/core/graphql/utils/gateway/LiteralConstantConverter.java
hypertrace-core-graphql-gateway-service-utils/src/test/java/org/hypertrace/core/graphql/utils/gateway/LiteralConstantConverterTest.java

ENG-17101: Support array types beyond string array in Literal converter

---

.snyk
hypertrace-core-graphql-grpc-utils/src/main/java/org/hypertrace/core/graphql/utils/grpc/DefaultGrpcChannelRegistry.java
hypertrace-core-graphql-grpc-utils/src/main/java/org/hypertrace/core/graphql/utils/grpc/GrpcChannelRegistry.java
hypertrace-core-graphql-platform/build.gradle.kts

Add support for optional configuration support to GrpcChannel

Support for GrpcChannelConfig in GrpcChannelRegistry

---

hypertrace-core-graphql-platform/build.gradle.kts

Updated a number of dependencies to latest to avoid vulnerabilities.

refactor: update dependencies

---

hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/schema/results/arguments/filter/FilterOperatorType.java
hypertrace-core-graphql-gateway-service-utils/src/main/java/org/hypertrace/core/graphql/utils/gateway/OperatorConverter.java
hypertrace-core-graphql-platform/build.gradle.kts

Propagating the changes from gateway-service(https://github.com/hypertrace/gateway-service/pull/136) to here, this PR adds `CONTAINS_KEY_LIKE` operator for doing a regex based search on map fields (on map key column).

feat: add CONTAINS_KEY_LIKE operator

---

.github/workflows/pr-test.yml
.snyk
hypertrace-core-graphql-grpc-utils/src/main/java/org/hypertrace/core/graphql/utils/grpc/DefaultGrpcChannelRegistry.java
hypertrace-core-graphql-grpc-utils/src/main/java/org/hypertrace/core/graphql/utils/grpc/GraphQlGrpcModule.java
hypertrace-core-graphql-grpc-utils/src/test/java/org/hypertrace/core/graphql/utils/grpc/DefaultGrpcChannelRegistryTest.java
hypertrace-core-graphql-impl/build.gradle.kts
hypertrace-core-graphql-impl/src/main/java/org/hypertrace/core/graphql/impl/GraphQlFactory.java
hypertrace-core-graphql-impl/src/main/java/org/hypertrace/core/graphql/impl/GraphQlModule.java
hypertrace-core-graphql-impl/src/test/java/org/hypertrace/core/graphql/impl/GraphQlModuleTest.java
hypertrace-core-graphql-service/src/main/java/org/hypertrace/core/graphql/service/GraphQlService.java

Small refactor to use the container's channel registry rather than building our own internally

refactor: use container-provided channel registry

---

build.gradle.kts
hypertrace-core-graphql-context/src/main/java/org/hypertrace/core/graphql/context/DefaultGraphQlRequestContextBuilder.java
hypertrace-core-graphql-context/src/main/java/org/hypertrace/core/graphql/context/GraphQlRequestContext.java
hypertrace-core-graphql-grpc-utils/src/main/java/org/hypertrace/core/graphql/utils/grpc/DefaultGrpcChannelRegistry.java
hypertrace-core-graphql-grpc-utils/src/main/java/org/hypertrace/core/graphql/utils/grpc/GraphQlGrpcContextBuilder.java
hypertrace-core-graphql-grpc-utils/src/main/java/org/hypertrace/core/graphql/utils/grpc/GraphQlGrpcModule.java
hypertrace-core-graphql-grpc-utils/src/main/java/org/hypertrace/core/graphql/utils/grpc/GrpcChannelRegistry.java
hypertrace-core-graphql-grpc-utils/src/main/java/org/hypertrace/core/graphql/utils/grpc/PlatformGrpcContextBuilder.java
hypertrace-core-graphql-grpc-utils/src/test/java/org/hypertrace/core/graphql/utils/grpc/PlatformGrpcContextBuilderTest.java
hypertrace-core-graphql-impl/src/main/java/org/hypertrace/core/graphql/impl/GraphQlModule.java
hypertrace-core-graphql-impl/src/test/java/org/hypertrace/core/graphql/impl/GraphQlModuleTest.java
hypertrace-core-graphql-log-event-schema/build.gradle.kts
hypertrace-core-graphql-platform/build.gradle.kts

- Add request ID, mapped to the new grpc request id
- Change how grpc channel registry is provided to make it more... guicey.

refactor: add request id, change how registry is provided

---

hypertrace-core-graphql-attribute-store/src/main/java/org/hypertrace/core/graphql/attributes/AttributeModelMetricAggregationType.java
hypertrace-core-graphql-attribute-store/src/main/java/org/hypertrace/core/graphql/attributes/AttributeModelTranslator.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/schema/attributes/MetricAggregationType.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/utils/attributes/AttributeModelMetricAggregationTypeConverter.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/utils/attributes/MetricAggregationTypeConverter.java
hypertrace-core-graphql-platform/build.gradle.kts

Adds DISTINCT_ARRAY aggregation type

feat: Add DISTINCT_ARRAY aggregation type

---

hypertrace-core-graphql-grpc-utils/src/main/java/org/hypertrace/core/graphql/utils/grpc/GrpcContextBuilder.java
hypertrace-core-graphql-grpc-utils/src/main/java/org/hypertrace/core/graphql/utils/grpc/PlatformGrpcContextBuilder.java
hypertrace-core-graphql-grpc-utils/src/test/java/org/hypertrace/core/graphql/utils/grpc/PlatformGrpcContextBuilderTest.java

Added the ability to restore the graphql request context from the grpc context. This is required for grpc instrumentation and interceptors which do not give direct access to the graphql context.
Updated unit tests

refactor: add ability to restore context

---

hypertrace-core-graphql-grpc-utils/src/main/java/org/hypertrace/core/graphql/utils/grpc/PlatformGrpcContextBuilder.java
hypertrace-core-graphql-platform/build.gradle.kts

Builder updates give it state, so making it a singleton. Also upgrading grpc context to improve logging and claim access.
Verified E2E

fix: make stateful builder singleton, upgrade context

---

hypertrace-core-graphql-context/src/main/java/org/hypertrace/core/graphql/context/DefaultGraphQlRequestContextBuilder.java
hypertrace-core-graphql-context/src/main/java/org/hypertrace/core/graphql/context/GraphQlRequestContext.java
hypertrace-core-graphql-context/src/test/java/org/hypertrace/core/graphql/context/DefaultGraphQlRequestContextBuilderTest.java
hypertrace-core-graphql-platform/build.gradle.kts
hypertrace-core-graphql-schema-registry/src/main/java/org/hypertrace/core/graphql/schema/registry/DefaultGraphQlSchemaRegistry.java
hypertrace-core-graphql-schema-registry/src/main/java/org/hypertrace/core/graphql/schema/registry/DefaultSchema.java
hypertrace-core-graphql-schema-registry/src/main/java/org/hypertrace/core/graphql/schema/registry/GraphQlAnnotatedSchemaMerger.java
hypertrace-core-graphql-schema-registry/src/test/java/org/hypertrace/core/graphql/schema/registry/GraphQlAnnotatedSchemaMergerTest.java

Updating the main GQL libs, which included a few breaking changes. The two main ones here are
- Schema Validation now requires every object to have at least one type. This makes sense, but causes issues with how we build partial schemas then merge them. Sidestepped the issue by adding placeholders to root schema so every partial schema passes validation, then stripping them out at the end (before validating one last time).
- The Context types were renamed and move around a bit. A few types were changed and fields removed. Updated our context based off it to extend the built in one and adjusted things here a bit.
Unit and ran E2E

refactor: update core gql libs

---

hypertrace-core-graphql-platform/build.gradle.kts

Update protobuf version. All API libs bring in varying versions, constraining to a more recent version.

refactor: update protobuf version

---

hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/request/DefaultResultSetRequestBuilder.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/request/ResultSetRequestBuilder.java

Expose a way to rebuild a result set request with extra filters. this makes it easy to, for example, add interceptors that apply mandatory filters.

refactor: add a way to rebuild a rs request with new filters

---

hypertrace-core-graphql-platform/build.gradle.kts

Pulling in https://github.com/hypertrace/java-grpc-utils/pull/44 (once merged, waiting on that)

fix: update grpc utils to clean up cves

---

hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/schema/typefunctions/UnknownScalar.java
hypertrace-core-graphql-common-schema/src/test/java/org/hypertrace/core/graphql/common/schema/scalars/UnknownScalarTest.java

The parseValue version of the unknown scalar was not correctly handling the raw values that are given when using a variable for an unknown value. It treated all inputs as AST objects. It now echos them back out, as unknown values have no specific type and they're left to the code to determine. Also fixed a buck where an error was returned rather than thrown which was hiding this issue in the past.
Added Unit tests and verified in local instance

fix: unknown scalar not handling variable values

---

hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/schema/results/arguments/filter/FilterOperatorType.java
hypertrace-core-graphql-gateway-service-utils/src/main/java/org/hypertrace/core/graphql/utils/gateway/OperatorConverter.java
hypertrace-core-graphql-platform/build.gradle.kts

NOT CONTAINS KEY operators on map attributes to check for (lack of) key presence. 
Depends on https://github.com/hypertrace/gateway-service/pull/162 being merged and published.

refactor: expose not contains key operator

---

hypertrace-core-graphql-platform/build.gradle.kts

This PR updates the `graphql-java` version to resolve a newly reported vulnerability (`CVE-2023-28867`)

chore: update graphql-java version

---

hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/fetcher/InjectableDataFetcher.java
hypertrace-core-graphql-context/src/main/java/org/hypertrace/core/graphql/context/DefaultGraphQlRequestContextBuilder.java
hypertrace-core-graphql-context/src/main/java/org/hypertrace/core/graphql/context/GraphQlRequestContext.java
hypertrace-core-graphql-log-event-schema/src/main/java/org/hypertrace/core/graphql/log/event/fetcher/LogEventFetcher.java
hypertrace-core-graphql-metadata-schema/src/main/java/org/hypertrace/core/graphql/metadata/fetcher/MetadataFetcher.java
hypertrace-core-graphql-metadata-schema/src/test/java/org/hypertrace/core/graphql/metadata/fetcher/MetadataFetcherTest.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/fetcher/ExportSpanFetcher.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/fetcher/SpanFetcher.java
hypertrace-core-graphql-trace-schema/src/main/java/org/hypertrace/core/graphql/trace/fetcher/TraceFetcher.java

GQL's context propagation was updated a long time back, and we've been relying on the deprecated mechanism (where an untyped object, rather than a map, is accessed). This puts the same value in the map and adds a simple util to access it in a type-safe way. All HTC usages have been updated

refactor: replace deprecated context fetch

---

hypertrace-core-graphql-platform/build.gradle.kts
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/dao/GatewayServiceSpanConverter.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/dao/GatewayServiceSpanRequestBuilder.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/request/DefaultSpanRequestBuilder.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/request/SpanRequest.java
hypertrace-core-graphql-span-schema/src/test/java/org/hypertrace/core/graphql/span/dao/DaoTestUtil.java
hypertrace-core-graphql-span-schema/src/test/java/org/hypertrace/core/graphql/span/dao/SpanLogEventRequestBuilderTest.java
hypertrace-core-graphql-trace-schema/build.gradle.kts
hypertrace-core-graphql-trace-schema/src/main/java/org/hypertrace/core/graphql/trace/dao/GatewayServiceTraceConverter.java
hypertrace-core-graphql-trace-schema/src/main/java/org/hypertrace/core/graphql/trace/dao/GatewayServiceTraceRequestBuilder.java
hypertrace-core-graphql-trace-schema/src/main/java/org/hypertrace/core/graphql/trace/request/DefaultTraceRequestBuilder.java
hypertrace-core-graphql-trace-schema/src/main/java/org/hypertrace/core/graphql/trace/request/TraceRequest.java
owasp-suppressions.xml

As part of supporting `fetch_total` as request in spans/traces API, this PR makes the corresponding changes at client side.
Ref PR: https://github.com/hypertrace/gateway-service/pull/169

feat: adding consumer support for new traces/spans api

---

hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/schema/operator/LogicalOperator.java

Added logical operator in hypertrace gql common schema

Add logical operator in hypertrace gql common schema

---

hypertrace-core-graphql-attribute-store/src/main/java/org/hypertrace/core/graphql/attributes/AttributeStore.java
hypertrace-core-graphql-attribute-store/src/main/java/org/hypertrace/core/graphql/attributes/CachingAttributeStore.java

Added ability to fetch on attribute id.

Added fetch attribute by id in Attribute Store

---

hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/SpanSchemaModule.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/joiner/DefaultSpanJoinerBuilder.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/joiner/SpanJoin.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/joiner/SpanJoiner.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/joiner/SpanJoinerBuilder.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/joiner/SpanJoinerModule.java
hypertrace-core-graphql-span-schema/src/test/java/org/hypertrace/core/graphql/span/joiner/SpanJoinerBuilderTest.java

chore | Add SpanJoiner based on spanId

---

hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/joiner/DefaultSpanJoinerBuilder.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/joiner/SpanJoiner.java
hypertrace-core-graphql-span-schema/src/test/java/org/hypertrace/core/graphql/span/joiner/SpanJoinerBuilderTest.java

chore | Add support for providing filters in spanJoiner
