hypertrace/hypertrace-core-graphql

.circleci/config.yml
.snyk
hypertrace-core-graphql-grpc-utils/build.gradle.kts

Upgrade grpcutils for 0.1.3 to support binary headers

Upgrade grpcutils for 0.1.3 to support binary headers

---

hypertrace-core-graphql-service/build.gradle.kts

chore: update platform service framework

---

.snyk

Ignore it in .snyk file since there is no patch for it

fix: snyk ionetty vulberability warning

---

hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/deserialization/CommonDeserializationModule.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/request/DefaultResultSetRequestBuilder.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/request/ResultSetRequest.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/request/ResultSetRequestBuilder.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/schema/results/arguments/space/SpaceArgument.java
hypertrace-core-graphql-common-schema/src/test/java/org/hypertrace/core/graphql/common/request/DefaultResultSetRequestBuilderTest.java
hypertrace-core-graphql-platform/build.gradle.kts
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/dao/GatewayServiceSpanRequestBuilder.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/schema/SpanSchema.java
hypertrace-core-graphql-trace-schema/src/main/java/org/hypertrace/core/graphql/trace/dao/GatewayServiceTraceRequestBuilder.java
hypertrace-core-graphql-trace-schema/src/main/java/org/hypertrace/core/graphql/trace/schema/TraceSchema.java

Add support for spaces on span + trace requests
hypertrace/hypertrace#142
Added unit test, deployed locally and verified.

feat: add support for spaces

---

hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/utils/TriConverter.java
hypertrace-core-graphql-platform/build.gradle.kts

Updated gateway version

---

hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/request/DefaultFilterRequestBuilder.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/schema/results/arguments/filter/FilterArgument.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/schema/results/arguments/filter/FilterType.java
hypertrace-core-graphql-metadata-schema/src/main/java/org/hypertrace/core/graphql/metadata/response/DefaultAttributeMetadata.java
hypertrace-core-graphql-metadata-schema/src/main/java/org/hypertrace/core/graphql/metadata/schema/AttributeMetadata.java

Remove previously deprecated code that is no longer in use via the UI (and hasn't been for at least 2 months). Deprecate more code (alternatives have been added, but UI has not yet been updated).
Verified unit tests, UI code, ran HT e2e with change and verified no issues.

chore: remove unused deprecated code, deprecate more

---

hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/schema/results/arguments/filter/FilterOperatorType.java
hypertrace-core-graphql-gateway-service-utils/src/main/java/org/hypertrace/core/graphql/utils/gateway/OperatorConverter.java
hypertrace-core-graphql-platform/build.gradle.kts

Added support for NOT IN operator

added support for not in operator

---

hypertrace-core-graphql-platform/build.gradle.kts

chore: update gateway service api

---

hypertrace-core-graphql-grpc-utils/src/main/java/org/hypertrace/core/graphql/utils/grpc/DefaultGrpcChannelRegistry.java

In certain scenarios, we were seeing errors on the first load after a GQL restart where multiple parallel requests may try to access the same channel in parallel.

fix: attempting to fix race for channels on startup

---

.github/CODEOWNERS
.github/workflows/pr-test.yml

Fix coverage upload to work on forks, update workflow code owners

ci: fix codeowners, forked tests

---

hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/export/ExportSpan.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/export/ExportSpanConstants.java
hypertrace-core-graphql-span-schema/src/main/java/org/hypertrace/core/graphql/span/fetcher/ExportSpanFetcher.java
hypertrace-core-graphql-span-schema/src/test/java/org/hypertrace/core/graphql/span/export/ExportSpanTest.java

Recently, we added support for log events associated with span. This change adds support in export API to download log event attributes associated with span.
- added unit test for log event validation
- verified locally running the docker-compose setup
example request:
```
{
exportSpans(
limit: 2
between: {startTime: "2021-05-25T15:56:00.979Z", endTime: "2021-05-25T16:56:00.979Z"}
filterBy: [{operator: EQUALS, value: "00000000000000004e85a9d8e602e1f4", type: ID, idType: TRACE}]
) {
result
}
}
```
example response:
```
{
"data": {
"exportSpans": {
"result": "{\"resourceSpans\":[{\"resource\":{\"attributes\":[{\"key\":\"service.name\",\"value\":{\"stringValue\":\"frontend\"}}]},\"instrumentationLibrarySpans\":[{\"spans\":[{\"traceId\":\"00000000000000004e85a9d8e602e1f4\",\"spanId\":\"4e85a9d …
```

feat: enhance export api with log event data

---

hypertrace-core-graphql-attribute-store/src/main/java/org/hypertrace/core/graphql/attributes/CachingAttributeStore.java
hypertrace-core-graphql-attribute-store/src/test/java/org/hypertrace/core/graphql/attributes/CachingAttributeStoreTest.java
hypertrace-core-graphql-platform/build.gradle.kts

Used the internal flag in attributeMetadata to filter out the attributes that we want to expose.

Filter out internal attributes using the internal flag

---

hypertrace-core-graphql-attribute-store/src/main/java/org/hypertrace/core/graphql/attributes/CachingAttributeStore.java
hypertrace-core-graphql-attribute-store/src/test/java/org/hypertrace/core/graphql/attributes/CachingAttributeStoreTest.java
hypertrace-core-graphql-platform/build.gradle.kts

Reverts hypertrace/hypertrace-core-graphql#79

Revert "Revert "Filter out internal attributes using the internal flag""

---

hypertrace-core-graphql-platform/build.gradle.kts

fix: upgrade vulnerable log4j

---

helm/templates/serviceconfig.yaml
helm/values.yaml
hypertrace-core-graphql-impl/src/main/java/org/hypertrace/core/graphql/impl/GraphQlFactory.java
hypertrace-core-graphql-service/src/main/java/org/hypertrace/core/graphql/service/DefaultGraphQlServiceConfig.java
hypertrace-core-graphql-service/src/main/java/org/hypertrace/core/graphql/service/GraphQlService.java
hypertrace-core-graphql-service/src/main/resources/configs/common/application.conf
hypertrace-core-graphql-spi/src/main/java/org/hypertrace/core/graphql/spi/config/GraphQlServiceConfig.java

Expose GQL query timeout for config

feat: expose config to change gql query timeout

---

.snyk
hypertrace-core-graphql-platform/build.gradle.kts

Updated grpc version deps

---

hypertrace-core-graphql-platform/build.gradle.kts

Upgraded versions of guava and grpc to avoid conflicts

Upgraded grpc and guava versions

---

hypertrace-core-graphql-platform/build.gradle.kts

refactor: update jackson

---

hypertrace-core-graphql-platform/build.gradle.kts

Updates gateway service version to propagate changes made in https://github.com/hypertrace/gateway-service/pull/145. (Adds DISTINCT function type support).

chore: update gateway service version for DISTINCT function type support

---

hypertrace-core-graphql-platform/build.gradle.kts

Update grpc utils to bring in dependency updates
https://github.com/hypertrace/java-grpc-utils/pull/38

refactor: update grpc utils

---

hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/schema/pair/KeyValuePair.java

feat: add key value pair

---

.github/workflows/merge-publish.yml
.github/workflows/pr-build.yml
.github/workflows/pr-test.yml
.github/workflows/publish.yml
build.gradle.kts
hypertrace-core-graphql-platform/build.gradle.kts
owasp-suppressions.xml

Update CI workflows to
- use newer runners
- user latest action versions
- remove redundant caching (now built into gradle actions)
- remove redundant check in build job (moved all verification into test job which was already running tests)
- replace snyk scan with owasp-based hypertrace action

ci: update ci workflows

---

hypertrace-core-graphql-platform/build.gradle.kts

This PR updates `graphql-java` version

chore: update graphql-java version

---

hypertrace-core-graphql-attribute-store/src/main/java/org/hypertrace/core/graphql/attributes/AttributeModelTranslator.java
hypertrace-core-graphql-attribute-store/src/main/java/org/hypertrace/core/graphql/attributes/AttributeModelType.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/schema/attributes/AttributeType.java
hypertrace-core-graphql-common-schema/src/main/java/org/hypertrace/core/graphql/common/utils/attributes/AttributeTypeConverter.java
hypertrace-core-graphql-common-schema/src/test/java/org/hypertrace/core/graphql/common/utils/attributes/AttributeTypeConverterTest.java
owasp-suppressions.xml

This PR adds support for double array attribute type

chore: add double array attribute type

---

hypertrace-core-graphql-platform/build.gradle.kts
owasp-suppressions.xml

This PR updates graphql-java version

fix: update graphql java version

---

hypertrace-core-graphql-platform/build.gradle.kts

Updating gql to non-vuln version again.

fix: update gql java lib

---

hypertrace-core-graphql-platform/build.gradle.kts

Updating grpcutils version to fix netty vuln

---

hypertrace-core-graphql-platform/build.gradle.kts

chore: upgrade grpc and grpcutils version due to vulns
